### ISSUE TITLE
部分emoji输出了多余的不可见字符

### ISSUE THREAD

**Issue by wizcas** [rime/rime-emoji#12]
我用的是小狼毫0.14.3。在输入emoji的时候，部分候选词后面出现了多余的字符，如：

![image](https://user-images.githubusercontent.com/2867434/62913155-a4088080-bdbd-11e9-8b57-87871ffc1165.png)

输出这种候选词后，emoji后面带了个不可见字符，需要退格两次才能删除emoji。请问大家有遇到这个问题吗？如何能解决呢。

*目前试了些emoji，有问题的包括：*

```
上（⬆️️）下（⬇️️）左（⬅️️）右（➡️️）有（🈶️️）爱（❤️️）新（🆕️️）信（✉️️）
```

**Comment by LEOYoon-Tsaw** [comment]
This might be the emoji selection. For these chars, there’s text appearance and color one, by adding the selection token, it is guarantee to be displayed in emoji way.
Windows’s treating emoji poorly, but the latest Windows should be generally better.

**Comment by wizcas** [comment]
The emoji characters that are input directly via Windows 10 Emoji panel (open by `Win+;`), however, can be shown and deleted correctly. I'm wondering how Microsoft makes that work...🤔
