### ISSUE TITLE
我启用 gbk 过滤后 emoji 就失效了

### ISSUE THREAD

**Issue by hosxy** [rime/rime-emoji#13]
我在方案配置文件里打开了 gbk 过滤 
```
 engine/filters:
    - simplifier
    - uniquifier
    - charset_filter@gbk
```
然后 emoji 就失效了

**Comment by lotem** [comment]
Emoji字符大多不屬於GBK字符集。

**Comment by AlynxZhou** [comment]
原来这边提过相关 issue，我今天也遇到[类似的问题](https://github.com/hosxy/rime-aurora-pinyin/issues/13)，现在 emoji 的 filter 是最先运行的所以会被过滤掉。我有个建议是把 `simplifier@emoji_suggestion` 添加到 `engine/filters/@last`，让它最后运行，就不会被过滤掉了，不知道会不会有什么潜在问题。

我能想到的一个潜在问题是 emoji 过滤器要求前面的输入必须是简体/繁体中文，所以如果某个奇怪的自定义输入方案是输入中文然后用过滤器把中文转换成其它文字，这个 emoji 过滤器添加到末尾就不会正常工作。不过我觉得我们大概不需要考虑这种奇怪的使用案例……
