### ISSUE TITLE
 部分 Emoji 后存在空格

### ISSUE THREAD

**Issue by Syusyuly** [rime/rime-emoji#19]
![image](https://user-images.githubusercontent.com/29004625/97200980-df3d7680-17ec-11eb-9c7f-b34b75fa1a38.png)
![image](https://user-images.githubusercontent.com/29004625/97201029-ebc1cf00-17ec-11eb-819f-433fa50fd418.png)
![image](https://user-images.githubusercontent.com/29004625/97201135-10b64200-17ed-11eb-8e03-293b371461cb.png)

**Comment by sgalal** [comment]
這個應該是 weasel 顯示的問題，不是 rime-emoji 的問題

打出來就可以看出是沒有空格的

**Comment by Syusyuly** [comment]
![image](https://user-images.githubusercontent.com/29004625/97202915-2fb5d380-17ef-11eb-9f8f-8a7c03a466d0.png)
![image](https://user-images.githubusercontent.com/29004625/97203130-64c22600-17ef-11eb-8bca-8986b184e694.png)
![image](https://user-images.githubusercontent.com/29004625/97203531-ea45d600-17ef-11eb-8a61-ce795e37202e.png)
似乎输出结果在部分软件中不能正常显示
图一为 UWP QQ 中输入及发送情况（不过在手机端查看消息时是正常显示的）
图二是键入的 Emoji 与复制的 Emoji 对比，键入的 Emoji 后伴随着不可编辑的空格
图三为在 Sublime Text 与 VS Code 的输入情况对比，Sublime Text 3 同样会有空格，不过可删除；VS Code 可正常显示。

**Comment by LEOYoon-Tsaw** [comment]
那個是U+FE0F，emoji variation selector，應用程序不應當單獨顯示之。沒有它有些地方emoji會顯示為普通文本（黑白）

**Comment by LEOYoon-Tsaw** [comment]
儘可能去掉了這個Selector，可以試一下MinimalSelector那個分支，看看有沒有問題

**Comment by Syusyuly** [comment]
目前一切正常，多谢
