### ISSUE TITLE
emoji not support for fcitx rime?

### ISSUE THREAD

**Issue by roachsinai** [rime/rime-emoji#2]
```
Installing: emoji_suggestion.yaml
Creating directory: /home/roach/.config/ibus/rime/opencc
Installing: opencc/emoji_category.txt
Installing: opencc/emoji.json
Installing: opencc/emoji_word.txt
Updated ~ 4 files from 1 packages in '/home/roach/.config/ibus/rime'
```

Can't fine file with `emoji` prefix under directory /home/roach/.config/fcitx/rime.

And as I install fctix-rime is there a way to not install all these yaml relate to ibus?

**Comment by lotem** [comment]
run `rime_frontend=fcitx-rime bash rime-install emoji`

see https://github.com/rime/plum#advanced-usage for details

**Comment by roachsinai** [comment]
Ok, thanks.
