### ISSUE TITLE
安装后仍然没有emoji

### ISSUE THREAD

**Issue by QuXiang-code** [rime/rime-emoji#25]
配置了custom，还是没有
![image](https://user-images.githubusercontent.com/70871914/109407622-4ea2bd00-79bd-11eb-98b3-3121530f1986.png)
![image](https://user-images.githubusercontent.com/70871914/109407633-5a8e7f00-79bd-11eb-911a-fe06135ef65b.png)

**Comment by LEOYoon-Tsaw** [comment]
你怎麼安裝的？說詳細點

**Comment by QuXiang-code** [comment]
> 你怎麼安裝的？說詳細點

1.将opencc文件夹放到用户文件夹下
2.用户文件夹下创建luna_pinyin_simp.custom.yaml（我用的明月简体）并添加
![image](https://user-images.githubusercontent.com/70871914/109422690-96eec900-7a17-11eb-9ec8-178a1e645f08.png)
3.检查emoji开启后输入发现并没有
![image](https://user-images.githubusercontent.com/70871914/109422727-c69dd100-7a17-11eb-9079-0febe4f9b849.png)
![Uploading image.png…]()

**Comment by LEOYoon-Tsaw** [comment]
第二步不對，直接把內容放進yaml，不要用@next、@before0這些。

**Comment by LEOYoon-Tsaw** [comment]
不知道啊，看不出來，你試試直接改`luna_pinyin_simp.yaml`吧，好像這不是自帶的方案，不用patch配置看看成不成

**Comment by jsdryan** [comment]
我的問題也一樣，系統是 Windows，使用的是「手動安裝」方案，將以下 3 個檔案放入指定的位置：
![image](https://github.com/rime/rime-emoji/assets/34669056/ba79fefb-04c9-44df-ada8-4a72fced5e5a)

然後我使用的方案是「朙月拼音·臺灣正體」，所以自建一個檔案為「`luna_pinyin_tw.custom.yaml`」：
![image](https://github.com/rime/rime-emoji/assets/34669056/2ba4c3f6-fd37-4ff8-b422-87b1b506a51e)

`luna_pinyin_tw.custom.yaml` 內容如下（依據你們的 README）：
![image](https://github.com/rime/rime-emoji/assets/34669056/3418221e-ac1f-4750-b559-52a8a9bcad30)

測試「笑」一樣沒有顯示。

**Comment by jsdryan** [comment]
解決了，README 文件語焉不詳。

正確的方法應是把 `opencc` 這整個資料夾複製到 `Rime` 內，變成 `Rime\opencc`，而不是單純複製 `opencc` 裡面的 3 個的的檔案。
