### ISSUE TITLE
请问匹配规则是什么样子的

### ISSUE THREAD

**Issue by ReadyP1ayer** [rime/rime-emoji#26]
![image](https://user-images.githubusercontent.com/39178989/109463253-a4e82c80-7a9f-11eb-9d16-832ef1217513.png)
![image](https://user-images.githubusercontent.com/39178989/109463305-b7fafc80-7a9f-11eb-8cf5-dcaaf4ac0694.png)
我查emoji_word.txt和emoji_category.txt里面的文字和emoji好像并不是对应的啊。另外，可以自定义emoji的匹配规则吗

**Comment by lotem** [comment]
可能兩幅圖用了不同的字體。

可以，這個配方的作者所做的您都可以做。
