### ISSUE TITLE
Squirrel上启用emoji后部分选项无法显示

### ISSUE THREAD

**Issue by hammerfunctor** [rime/rime-emoji#27]
如图: 
<img width="141" alt="image" src="https://user-images.githubusercontent.com/65394269/110272563-77eacb00-8005-11eb-827c-0977bf008a79.png">
但是用TextEdit打开`emoji_word.txt`所有emoji显示都是正常的。可能是字体的问题？
如果确实是字体的问题，要怎样为汉字和emoji启用不同的字体 (指`Apple Color Emoji`)

感谢🙏🏻！

**Comment by LEOYoon-Tsaw** [comment]
那不是繪文字。繪文字毋需專門設定字體，系統會自動適用Apple Color Emoji字體

**Comment by hammerfunctor** [comment]
> 那不是繪文字。繪文字毋需專門設定字體，系統會自動適用Apple Color Emoji字體

确实，关闭emoji后仍有这个问题
