### ISSUE TITLE
有一些符号无法正常展示，在rime上展示为？， 如何过滤

### ISSUE THREAD

**Issue by TYZRPVX** [rime/rime-emoji#31]
![image](https://user-images.githubusercontent.com/7645818/118751386-cd5c1780-b893-11eb-8e5b-3111ea0c80b9.png)

**Comment by LEOYoon-Tsaw** [comment]
你的字體不支持，自己刪掉就行了。

**Comment by TYZRPVX** [comment]
> 你的字體不支持，自己刪掉就行了。

是否有过滤的方法？使用opencc的emoji词库，逐个删除比较繁琐

**Comment by TYZRPVX** [comment]
@LEOYoon-Tsaw

**Comment by LEOYoon-Tsaw** [comment]
我怎麼知道你那支持顯示什麼，不支持什麼，當然只有你自己來啦，對不對呀

**Comment by TurnOffNOD** [comment]
> 你的字體不支持，自己刪掉就行了。

那么在linux下，有哪些字体是支持这些utf-8的emoji符号呢？
