### ISSUE TITLE
自动安装&自助安装均无效

### ISSUE THREAD

**Issue by twlz0ne** [rime/rime-emoji#32]
![image](https://user-images.githubusercontent.com/2653486/132530027-d2c37214-794b-47ad-afe2-7a1ab7e28d5a.png)

`C-n`

![image](https://user-images.githubusercontent.com/2653486/132532090-e85faa4b-c2d1-4add-a5cb-4b58c162355b.png)

`C-n`

![image](https://user-images.githubusercontent.com/2653486/132532158-04517e49-6c81-4147-9e4e-63bd4e26ca31.png)

#### 自动安装

- `bash rime-install emoji:customize:schema=luna_pinyin`

在 `luna_pinyin.custom.yaml 中添加了下内容：

```yaml
# Rx: emoji:customize:schema=luna_pinyin {
  - patch/+:
      __include: emoji_suggestion:/patch
# }
```

- 部署出错：

    E0908 22:11:39.110625 207474688 config_compiler.cc:428] resource could not be loaded: emoji_suggestion
    E0908 22:11:39.110667 207474688 config_compiler.cc:536] unresolved dependency: Include(emoji_suggestion:/patch)
    E0908 22:11:39.110707 207474688 config_compiler.cc:536] unresolved dependency: PendingChild(luna_pinyin.custom:/__patch/@1/patch/+)
    E0908 22:11:39.110746 207474688 config_compiler.cc:536] unresolved dependency: PendingChild(luna_pinyin.custom:/__patch/@1)
    E0908 22:11:39.110786 207474688 config_compiler.cc:536] unresolved dependency: PendingChild(luna_pinyin.custom:/__patch)
    

观察到自动安装并未复制 opencc 文件夹，于是手动复制，重新依然部署失败。

#### 自助安装

```sh
$ cp -r rime-emoji/opencc ~/Library/Rime/
$ cat<<EOF>~/Library/Rime/luna_pinyin.schema.custom.yaml
# encoding: utf-8
patch:
  switches/@next:
    name: emoji_suggestion
    reset: 1
    states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
  'engine/filters/@before 0':
    simplifier@emoji_suggestion
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    tips: all
EOF
```

部署成功，但仍然无效。

### 系统&版本

- macOS 10.12.6
- squirrel 0.15.2 + luna_pinyin

**Comment by LEOYoon-Tsaw** [comment]
直接接在後面肯定不行啊，關於如何使用custom打patch：
https://github.com/rime/home/wiki/CustomizationGuide

**Comment by twlz0ne** [comment]
[**@LEOYoon-Tsaw**](https://github.com/LEOYoon-Tsaw) commented on [Sep 9, 2021, 12:48 AM GMT+8](https://github.com/rime/rime-emoji/issues/32#issuecomment-915401459 "2021-09-08T16:48:40Z - Replied by Github Reply Comments"):
> 直接接在後面肯定不行啊

指的是哪部分？自助安装的 `luna_pinyin.schema.custom.yaml` 文件？我是全量覆盖，不是追加。

**Comment by LEOYoon-Tsaw** [comment]
看不懂。參照https://github.com/rime/home/wiki/CustomizationGuide，手動修改吧。

**Comment by twlz0ne** [comment]
把 patch 写到 `luna_pinyin_simp.custom.yaml` 生效了：

```sh
$ cat <<EOF> ~/Library/Rime/luna_pinyin_simp.custom.yaml
# encoding: utf-8
patch:
  switches/@next:
    name: emoji_suggestion
    reset: 1
    states: [ "🈚️️\uFE0E", "🈶️️\uFE0F" ]
  'engine/filters/@before 0':
    simplifier@emoji_suggestion
  emoji_suggestion:
    opencc_config: emoji.json
    option_name: emoji_suggestion
    tips: all
EOF
```

或者:

```sh
$ cp ~/repos/rime-emoji/emoji_suggestion.yaml ~/Library/Rime/
$ cat <<EOF> ~/Library/Rime/luna_pinyin_simp.custom.yaml
patch:
  __include: emoji_suggestion:/patch
EOF
```

然后我又恢复原状，用**自动安装**试了一遍：

```sh
$ ~/repos/rime-plum/rime-install emoji:customize:schema=luna_pinyin_simp
Installing for Rime frontend: rime/squirrel
Updating package: emoji
Already up to date.
Installing recipe: emoji:customize
- option: schema=luna_pinyin_simp
Patching: luna_pinyin_simp.custom.yaml
Updating patch.
No files updated.
```

发现自动安装只更新 `*.custom.yaml`，并没有复制 `emoji_suggestion.yaml` 所以不生效，于是手动复制：

```sh
$ cp ~/repos/rime-emoji/emoji_suggestion.yaml ~/Library/Rime/
```

再次部署，果然生效了。

**Comment by LEOYoon-Tsaw** [comment]
原來是弄錯了文件

**Comment by lotem** [comment]
​需要先安裝`emoji`配方，再爲自選的輸入方案啓用
