### ISSUE TITLE
请问有办法唤出emoji面板并选择特定的表情符号吗

### ISSUE THREAD

**Issue by oodzchen** [rime/rime-emoji#40]
有时候我想输入某个表情符，但是根据输入建议找不到，比如我想输入笑的两眼飙泪的表情：[😂](https://emojipedia.org/face-with-tears-of-joy/)，我输入“笑死”，建议的是“🤣”，是一个脑袋斜着的表情，虽说意思相近，但并不是我要找的。我尝试用别的词语，比如“笑”、“笑哭”、“哈哈哈哈”等都没找到我要的符号，所以我在想，是不是应该有办法直接打开emoji面板，专门搜索和选择emoji，以方便输入呢。

**Comment by LEOYoon-Tsaw** [comment]
你可以改opencc的文件，把😂笑死加進去即可。面板沒有。
