### ISSUE TITLE
emoj是不是太多重复了

### ISSUE THREAD

**Issue by vitock** [rime/rime-emoji#41]
![图片](https://user-images.githubusercontent.com/6203946/206337144-c5be3f6f-8a1d-46dd-bda7-62862eea52e1.png)

输入qiche ，本意是骑车，
但是要翻到第三页才有，前面都被各种各样的emoj覆盖了。

**Comment by LEOYoon-Tsaw** [comment]
誰讓普通話同音呢

**Comment by vitock** [comment]
> 誰讓普通話同音呢

我的意思是，实际上绝大部分人只要随意一个emoj表示意义就行了，根本不在乎是那一种汽车

能不能把相同意思的emoj 放在后面？确保每一页只有一个emoj（不知道软件支持不支持这种

表情虽然有趣，但毕竟不能当作主食

**Comment by LEOYoon-Tsaw** [comment]
你可以刪掉emoji_category.txt，emoji.json也對應該該就行了
