### ISSUE TITLE
请问一下安装之后emoji没有颜色，怎么处理？

### ISSUE THREAD

**Issue by alpha2016** [rime/rime-emoji#5]
![snipaste_2019-01-22_17-01-51](https://user-images.githubusercontent.com/13464027/51523846-80084080-1e67-11e9-9f19-7e77edb86d5d.jpg)

大概就是这样的，有什么办法让他显示为彩色吗？windows10 系统，试过换成明兰字体，但是无效，还是这种情况。

**Comment by zhuxiaoxi** [comment]
是字体问题。并不是每一种字体都绘制了emoji，字体有fullback顺序，需要安装并设置彩色的emoji字体

**Comment by yzlnew** [comment]
> 是字体问题。并不是每一种字体都绘制了emoji，字体有fullback顺序，需要安装并设置彩色的emoji字体

@zhuxiaoxi 问一下，你用了什么字体

**Comment by alpha2016** [comment]
> 是字体问题。并不是每一种字体都绘制了emoji，字体有fullback顺序，需要安装并设置彩色的emoji字体

+1 想问一下是什么字体，windows10 自带一套emoji吧？

**Comment by yzlnew** [comment]
我觉得是调用了 Win 10 的 Emoji 但是没有正确渲染？

**Comment by zhuxiaoxi** [comment]
macOS默认的就是彩色，我没安装其他的

**Comment by yzlnew** [comment]
mac 能正确渲染而已，我两个系统都用，win 不行

**Comment by zhuxiaoxi** [comment]
这种字体网上一搜就有，你试试这个https://github.com/eosrei/twemoji-color-font

**Comment by yzlnew** [comment]
确认了一下，还是不可以的。Windows 自带的 `Segoe UI Emoji` 在其他应用里也能渲染出颜色，Rime 里不可以。

**Comment by zhuxiaoxi** [comment]
好吧，没帮上忙，我以为Windows上是直接替换掉系统的字体就可以。

**Comment by alpha2016** [comment]
> 好吧，没帮上忙，我以为Windows上是直接替换掉系统的字体就可以。

没事没事，也多谢了，至少尝试了一下

**Comment by zYeoman** [comment]
Windows实现彩色emoji，需要使用DirectWrite渲染。（用chrome测试过，开启DW是彩色，关闭DW是黑白）

**Comment by TomatoFryEggs** [comment]
所以目前Win上这个是无解？

**Comment by alpha2016** [comment]
> 所以目前Win上这个是无解？

当时我是没找到方法，就切换回 M$ 系统输入法了

**Comment by LEOYoon-Tsaw** [comment]
這個目前Windows上無解，要換輸入法框架才能支持彩色

**Comment by TurnOffNOD** [comment]
> 
> 
> 现在win10好像已经支持这个表情了，今天试了试是可以显示的

是支持，只不过rime上不显示颜色……

**Comment by TurnOffNOD** [comment]
> 
> 
> ![snipaste_2019-01-22_17-01-51](https://user-images.githubusercontent.com/13464027/51523846-80084080-1e67-11e9-9f19-7e77edb86d5d.jpg)
> 
> 大概就是这样的，有什么办法让他显示为彩色吗？windows10 系统，试过换成明兰字体，但是无效，还是这种情况。

lz图里面的数学符号是安装的什么输入法？

**Comment by zombie110year** [comment]
Windows 10 不知道，不过我在 Linux 里设置 fcitx5 的字体就可以显示了：
![image](https://user-images.githubusercontent.com/36528430/165779935-7f32b3de-6d0c-4b92-a766-8d93908db9a2.png)
具体是修改 `.local/share/fcitx5/conf/classicui.conf`，添加一项 `Font="Noto Color Emoji"` （或者其他有颜色的 emoji 字体）

**Comment by yfdyh000** [comment]
https://learn.microsoft.com/zh-cn/windows/win32/directwrite/color-fonts#using-color-fonts-with-directwrite-and-direct2d
https://github.com/rime/weasel/search?q=DrawText
也许程序代码加上`D2D1_DRAW_TEXT_OPTIONS_ENABLE_COLOR_FONT`能解决，如果不会引起其他bug。

但小狼毫的开发目前停滞了。https://github.com/rime/weasel/issues/784

**Comment by yfdyh000** [comment]
发现fork还在积极开发（不在主分支），已进行了相关开发：
https://github.com/fxliang/weasel/commits/dev2
https://github.com/fxliang/weasel/commit/3a08f745a52b94e345ddfc3aee1a6897356003db

**Comment by rtransformation** [comment]
我也是昨天才看到这个新的fock，现在已经支持了
![image](https://user-images.githubusercontent.com/11702676/203958296-1db41d90-99ad-4000-94fa-9708451a44ba.png)

**Comment by FrankDong0** [comment]
> 我也是昨天才看到这个新的fock，现在已经支持了 ![image](https://user-images.githubusercontent.com/11702676/203958296-1db41d90-99ad-4000-94fa-9708451a44ba.png)

纯新人， 请问该怎么使用这个fork呢？
