### ISSUE TITLE
「🤡」應歸於「小丑」而非「小醜」

### ISSUE THREAD

**Issue by ksqsf** [rime/rime-emoji#50]
按字典釋義：

小醜：稱小人、盜匪等

小丑：戲劇中的丑角等

**Comment by LEOYoon-Tsaw** [comment]
小醜就是醜陋的意思，和丑（地支第二）無關

**Comment by ksqsf** [comment]
Emoji「🤡」是「clown」意，而戲班「丑角」均作「丑」而非「醜」。

<img width="581" alt="image" src="https://github.com/rime/rime-emoji/assets/23358293/f4ac4291-0dc0-4f0e-ad3a-33c5928f223c">
