### ISSUE TITLE
请问如何将suggestion改为简体中文？

### ISSUE THREAD

**Issue by Leslie307** [rime/rime-emoji#7]
将emoji应用到明月拼音，使用明月拼音简化字，表情的suggestion是繁体字，请问如何显示简体字，我看emoji_word.txt和emoji_category.txt中繁体字和简体字是都有的。

**Comment by zhuxiaoxi** [comment]
请确认是否正确安装到明月拼音简化字。
安装方法README里有呀。
```
bash rime-install emoji:customize:schema=luna_pinyin_simp
```

**Comment by BlindingDark** [comment]
双拼好像默认是不行的

**Comment by tuberry** [comment]
没有集成在switcher，不过把这里
https://github.com/rime/rime-emoji/blob/6ee7ce65b21cd0fd8df0306a7c77a067f18fb55f/emoji_suggestion.yaml#L8
0改成1就行了
