### ISSUE TITLE
在终端下输入emoji无法正确显示

### ISSUE THREAD

**Issue by nb5p** [rime/rime-emoji#8]
rime-emoji版本：安装于2019年4月
rime版本：0.11
macOS版本：14.04
iTerm2版本：3.2.9
zsh版本：5.7.1

实际的效果：以草莓为例，其他表情均存在问题。终端下的emoji输入后会有个`<fe0f>`的标记，显示为`🍓️<fe0f>`。见下图。
<img width="387" alt="屏幕快照 2019-05-06 19 54 50" src="https://user-images.githubusercontent.com/2098464/57223527-f73d9b00-7038-11e9-8b24-b467017d4e78.png">

预期的效果：当输入草莓的emoji时，没有`<fe0f>`，只显示🍓️

测试的终端：iTerm2 Mac系统自带的终端 Hyper等

这些终端下的表现：
- iTerm2 最上方的图片为iTerm2的效果。
- Mac自带的终端 在插入emoji后显示是这样的`🍓️`，按删除键，可以删除删除，如果再按删除键可以删除掉命令行的提示符。
- Hyper 与iTerm2表现相同。

换输入法测试：使用系统自带的输入法、搜狗输入法、Mac系统内置的插入表情符号工具。表现均和预期一样。

**Comment by zhuxiaoxi** [comment]
Mac自带终端会出现这种效果肯定与`<fe0f>`这个标记有关，如果使用Rime输入法将表情输入法到其他位置（比如浏览器的地址栏），再粘贴到终端也会有这个标记。其他输入法不会。

**Comment by yzlnew** [comment]
可以复现。这和 Emoji 的实现有关，`U+FE0F` 指定了以彩色呈现 Emoji，可以参考[这个](https://www.jianshu.com/p/9682f8ce1260)。

**Comment by zhuxiaoxi** [comment]
看了这篇文章，有所启发。就下了这个软件，还不太会设置，但是可以看出来这个Rime的输出了和其他输入法不一样的结果。
<img width="583" alt="屏幕快照 2019-05-10 23 25 57" src="https://user-images.githubusercontent.com/2098464/57538853-d4ceb900-737b-11e9-878d-88726f751388.png">

**Comment by zhuxiaoxi** [comment]
使用在线十六进制转换工具的结果（对于🍓️）：
Mac `d83cdf53`
Rime `d83cdf53fe0f`

**Comment by LEOYoon-Tsaw** [comment]
更新一下，最新的碼表已經解決

**Comment by purejoy** [comment]
@LEOYoon-Tsaw 
Linux底下用最新的码表还是不行。
librime: 最新
zsh：5.8
![2020-04-30_21-23](https://user-images.githubusercontent.com/3711998/80716727-969d4d00-8b2a-11ea-8312-bb9b2f6ccff1.png)

**Comment by sgalal** [comment]
U+FE0F 是選擇器，有是正常的。如果終端顯示有問題，那說明是終端的問題嘛。

**Comment by purejoy** [comment]
感谢提醒！
相同的情形我在Fish和Bash中对比了一下，发现是Zsh的问题。
查询了zsh的[官方文档](http://zsh.sourceforge.net/FAQ/zshfaq05.html)，找到`COMBINING_CHARS`这个选项，默认是关闭的。在`.zshrc`中加入：
`setopt COMBINING_CHARS` 
可以解决这个问题。
