### ISSUE TITLE
如何撤銷在輸入方案中添加候選繪文字這一過程？

### ISSUE THREAD

**Issue by Sponge-bink** [rime/rime-emoji#9]
如題，很早添加的 emoji 現在不想再要。macOS 10.14.5，Squirrel 0.11.0 但配置是從 0.9.20 繼承來的。

另外 Deploy 一直報錯，去 $TMPDIR 裏看 log 也提示替身找不到原身，‘ERROR’、‘INFO’、和 ‘WARNING’ 都這麼提示。所以順便也提一下這個 issue……

**Comment by Sponge-bink** [comment]
補充：不記得當時用了什麼方法在輸入方案中添加候選繪文字的了。Deploy 一直報錯但是換了新電腦搬來舊配置也一直都能打字。

**Comment by Sponge-bink** [comment]
更新：我導出了用戶詞典，把裏面的 emoji 一個一個對着打出來然後按 Fn + Shift + Delete 刪除掉的……

**Comment by lotem** [comment]
早期的绘文字方案用的是独立的反查词典。不会记入主方案的用户词典。
楼主可能用了其他的方案。
